version: '3.1'
services:
  stats-server:
    build: statisticService
    container_name: stats
    depends_on:
      - stats-db
    ports:
      - "9090:9090"

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6543:5433"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=explore-with-me-statistic

  ewm-service:
    build: mainService
    container_name: main
    depends_on:
      - ewm-db
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=explore-with-me-main
